// space — the movement-play SPACE CHECK report (phase 4, 2026-09-25): where the check passes and why it stops where it
// does not, on the synthetic cameras and on the owner's own takes, and what it costs a frame.
//
//   node node_modules/tsx/dist/cli.mjs scripts/body/space.mts [--out <file>]
//   TAKES=~/Downloads/fel-pose-takes-….json node node_modules/tsx/dist/cli.mjs scripts/body/space.mts
//
// Default out: ~/Claude/outbox/finish-release/movementplay/p4/SPACE.md (outside the repo). Numbers only: no camera, no
// server, deterministic (the fixtures and the scripted streams are seeded). The gate asserting these is
// lib/move/spaceGate.test.ts. TAKES= runs a /dev/pose-record file's takes through the same check (the 'space' take is
// the one the gate's real-camera row waits for): each one's last stage and line, and the rule that stopped it.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { homedir } from 'node:os';
import { execSync } from 'node:child_process';
import * as scNs from '../../lib/move/spaceCheck.ts';
import * as kitNs from '../../lib/pose/streamKit.ts';
import * as synNs from '../../lib/pose/synth.ts';
import type { PoseFixture, CameraSpec } from '../../lib/pose/synth.ts';
import type { PoseFrame } from '../../lib/pose/landmarks.ts';
import type { SpaceState } from '../../lib/move/spaceCheck.ts';
// the app's modules load as CommonJS under tsx: the named exports sit on the default
const unwrap = <T,>(ns: T): T => ((ns as unknown as { default?: T }).default ?? ns);
const SC = unwrap(scNs);
const { SpaceCheck, PLAY_FILL_MIN, PLAY_FILL_MAX, HEADROOM_JUMP_M, SWAP_M, MIN_POSE_HZ } = SC;
const { reshoot, spaceSession } = unwrap(kitNs);
const { synthesize } = unwrap(synNs);

const FIX = join(process.cwd(), 'lib/pose/__fixtures__');
const argOut = process.argv.indexOf('--out');
const OUT = argOut > 0 ? process.argv[argOut + 1] : join(homedir(), 'Claude/outbox/finish-release/movementplay/p4/SPACE.md');
const names: string[] = JSON.parse(readFileSync(join(FIX, 'index.json'), 'utf8')).map((f: { name: string }) => f.name);
const fixture = (n: string) => JSON.parse(readFileSync(join(FIX, `${n}.json`), 'utf8')) as PoseFixture;
const head = (() => {
  try {
    const h = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
    return execSync('git status --porcelain -- lib/move lib/pose lib/mirror', { encoding: 'utf8' }).trim() ? `${h} + the working tree` : h;
  } catch { return '?'; }
})();

const run = (frames: PoseFrame[], aspect?: number): SpaceState[] => { const c = new SpaceCheck({ aspect }); return frames.map((f) => c.push(f)); };
/** What a run ended on: ready, or the stage and the rule that held it there. */
const verdict = (states: SpaceState[]): string => {
  const last = states[states.length - 1];
  if (!last) return 'no frames';
  if (states.some((s) => s.ready)) return '**OK**';
  return last.issue ?? (last.stage === 'arms' && last.headroom && !last.headroom.ok ? (last.headroom.stepBack ? 'headroom' : 'raise camera') : `${last.stage}: ${last.instruction.rule}`);
};
const f2 = (n: number | null | undefined) => (n == null || !Number.isFinite(n) ? '–' : n.toFixed(2));
const f3 = (n: number | null | undefined) => (n == null || !Number.isFinite(n) ? '–' : n.toFixed(3));
const lines: string[] = [];
const out = (s = '') => lines.push(s);

out('# P4 space check: SPACE.md');
out();
out(`Generated by \`scripts/body/space.mts\` at \`${head}\` (${new Date().toISOString().slice(0, 10)}). Numbers only: seeded synthetic cameras and the owner's DeepMotion fixtures. The gate asserting them is \`lib/move/spaceGate.test.ts\`.`);
out();
out(`Fill band ${f3(PLAY_FILL_MIN)}–${f3(PLAY_FILL_MAX)} (nose → lower ankle, share of the frame) · design jump ${HEADROOM_JUMP_M} m above the raised hands · one body: a hip step of ${SWAP_M} m in a frame's time · pose rate ≥ ${MIN_POSE_HZ} Hz for a read jump height.`);
out();

// ── 1. the device matrix ──
const LENSES: [string, Partial<CameraSpec>, number[]][] = [
  ['webcam 4:3 60°', { width: 640, height: 480, hfovDeg: 60 }, [1.0, 1.2]],
  ['webcam 4:3 60°, low', { width: 640, height: 480, hfovDeg: 60 }, [0.75]],
  ['webcam 16:9 70°', { width: 1280, height: 720, hfovDeg: 70 }, [1.1]],
  ['webcam 16:9 78°', { width: 1280, height: 720, hfovDeg: 78 }, [1.1]],
  ['phone on its side 16:9 65°', { width: 1280, height: 720, hfovDeg: 65 }, [1.1]],
  ['phone upright 9:16', { width: 720, height: 1280, hfovDeg: 43 }, [1.2]],
];
const DISTS = [2.5, 3.0, 3.5, 4.0, 4.5];
out('## 1. Where it passes (synth session: stand → reach → lower → stand, seed 11)');
out();
out('"OK" = ready by the end of the 5 s session; otherwise the rule that stopped it.');
out();
out(`| Lens | Lens height | ${DISTS.map((d) => `${d.toFixed(1)} m`).join(' | ')} |`);
out(`|---|---|${DISTS.map(() => '---').join('|')}|`);
for (const [label, lens, heights] of LENSES) {
  for (const h of heights) {
    const cells = DISTS.map((d) => {
      const cam = { ...lens, distance: d, heightM: h };
      return verdict(run(synthesize(spaceSession(), { camera: cam, seed: 11 }).frames, (lens.width ?? 4) / (lens.height ?? 3)));
    });
    out(`| ${label} | ${h.toFixed(2)} m | ${cells.join(' | ')} |`);
  }
}
out();
out('The lever is `HEADROOM_JUMP_M` (plan §12 R1): at 0.35 m the band\'s top moves from 0.565 to about 0.60, and a 4:3 webcam passes from about 3.1 m.');
out();

// ── 2. the owner's takes ──
out("## 2. The owner's takes (DeepMotion fixtures)");
out();
out('| Take | As shot (3 m): fill median | As shot: issues | From 3.6 m: issues | Swap fired (as shot / 15 Hz / 3.6 m) |');
out('|---|---|---|---|---|');
for (const n of names) {
  const fx = fixture(n);
  const a = run(fx.frames), b = run(reshoot(fx, { distance: 3.6, heightM: 1.2 }));
  const fills = a.map((s) => s.check.reading.fill).filter((x) => x > 0).sort((x, y) => x - y);
  const issues = (ss: SpaceState[]) => [...new Set(ss.flatMap((s) => s.check.issues).filter((i) => i !== 'noBody'))].join(', ') || 'none';
  const swaps = [fx.frames, fx.frames.filter((_, i) => i % 2 === 0), reshoot(fx, { distance: 3.6, heightM: 1.2 })]
    .map((fr) => run(fr).filter((s) => s.issue === 'swap').length).join(' / ');
  out(`| ${n} | ${f3(fills[fills.length >> 1])} | ${issues(a)} | ${issues(b)} | ${swaps} |`);
}
out();

// ── 3. the recorder's takes, if given ──
out('## 3. /dev/pose-record takes');
out();
const takesFile = process.env.TAKES;
if (!takesFile) {
  out('None given. No `fel-pose-takes-*.json` exists on this Mac (the recorder saves through a browser download, usually to ~/Downloads). **The real-camera row of the gate (G3) stays open** until the owner records the recorder\'s `space` take at his play spot and this script is run with `TAKES=<file>`.');
} else if (!existsSync(takesFile)) {
  out(`\`${takesFile}\` does not exist.`);
} else {
  const file = JSON.parse(readFileSync(takesFile, 'utf8')) as { device: string; takes: { id: string; label: string; video: { width: number; height: number }; detectFps: number; frames: PoseFrame[] }[] };
  out(`From \`${takesFile}\` (${file.device}).`);
  out();
  out('| Take | Video | Detect fps | Ready | Last stage | Last line | Stopped by |');
  out('|---|---|---|---|---|---|---|');
  for (const t of file.takes) {
    const states = run(t.frames, t.video.width / t.video.height);
    const last = states[states.length - 1];
    out(`| ${t.id}${t.id === 'space' ? ' (**the gate\'s**)' : ''} | ${t.video.width}×${t.video.height} | ${t.detectFps} | ${states.some((s) => s.ready) ? 'yes' : 'no'} | ${last?.stage ?? '–'} | ${last?.instruction.id ?? '–'} | ${verdict(states)} |`);
  }
}
out();

// ── 4. the cost ──
const ms: number[] = [];
for (const seed of [17, 23, 41]) {
  const c = new SpaceCheck();
  for (const f of synthesize(spaceSession({ end: 8 }), { camera: { distance: 3.6, heightM: 1.2 }, seed }).frames) {
    const t = performance.now(); c.push(f); ms.push(performance.now() - t);
  }
}
ms.sort((a, b) => a - b);
out('## 4. Cost');
out();
out(`\`SpaceCheck.push\` in node: median ${f3(ms[ms.length >> 1])} ms, p90 ${f3(ms[Math.floor(ms.length * 0.9)])} ms a frame over ${ms.length} frames (budget: 0.5 ms). It runs only while the check does (READY, or a check over a pause); in play the reader owns the body.`);
out();

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n'));
console.log(`wrote ${OUT} (${lines.length} lines)`);
console.log(lines.slice(0, 40).join('\n'));
