/**
 * The story's data format (ADVENTURE PLAN, "Story": "the format is fixed now so Phase B's placeholders match it").
 * Pure types and validators: no Babylon, no DOM. The data itself is JSON under `lib/adventure/story/`:
 *
 *   index.json                 the cast, the hub, and the chapters in order (each mapped to a world)
 *   chapters/<nn>-<slug>.json  one chapter: its world, its beats, its lines
 *   manuscript/<nn>-<slug>.json  (Phase E, generated by scripts/adventure/import-autobiography.ts) the book's
 *                              paragraphs with stable ids (`p001`…); a line drawn from the book says `sourceRef: "p012"`
 *
 * THE PLACEHOLDER RULE (plan, "Placeholders"; owner, 2026-10-06). Until the owner sends the autobiography, a chapter
 * carries `placeholder: true` AND its title starts `[PLACEHOLDER]`; the dialogue box shows a PLACEHOLDER tag on every
 * line of such a chapter. A chapter that loses either mark fails `validateChapter`, and so does a chapter that claims to
 * be from the book (`placeholder: false`) with no `sourceRef` on any line, or with a `sourceRef` that points at nothing.
 *
 * THE BEATS (plan): cutscene, dialogue, objective, fight, boss, travel, choice. A beat may set flags when it completes,
 * name a checkpoint (`{worldId, spawnId}`, never raw coordinates: the open world streams later), learn a spell, or
 * (the Chapter 1 finale only) fuse the party for the first time.
 *
 * IP LINE: every name in the data is generic, and every placeholder name says `[PLACEHOLDER]`.
 */

export const STORY_FORMAT_VERSION = 1 as const;
export const PLACEHOLDER_PREFIX = '[PLACEHOLDER]';

export const BEAT_KINDS = ['cutscene', 'dialogue', 'objective', 'fight', 'boss', 'travel', 'choice'] as const;
export type BeatKind = (typeof BEAT_KINDS)[number];

export type FlagValue = boolean | number | string;

/** Who says a line: a cast id from index.json, or the two party ids the runner resolves at play time. */
export type SpeakerId = string;
/** The partner speaks under the name the player gave it; the player under "YOU". */
export const PARTY_SPEAKERS = ['partner', 'player'] as const;

export interface StoryLine {
  /** Unique inside its chapter. */
  id: string;
  speaker: SpeakerId;
  text: string;
  /** The manuscript paragraph this line is drawn from (Phase E). Absent on a placeholder line. */
  sourceRef?: string;
  /** A recorded take's clip id (audio/voice bakedLine) when the owner records it; absent = the browser voice (TTS). */
  voice?: string;
}

export interface StoryChoice {
  id: string;
  text: string;
  /** The flag this choice sets (`flags[flag] = value`, default the choice id). */
  flag?: string;
  value?: FlagValue;
}

export interface BeatBase {
  id: string;
  kind: BeatKind;
  /** Saved as the checkpoint when the beat starts: a respawn and a resume land here. */
  checkpoint?: { worldId: string; spawnId: string };
  /** Flags set when the beat completes. */
  setFlags?: Record<string, FlagValue>;
  /** A spell learned when the beat completes ("learned through the story"); `partner.bolt` = the partner's element bolt. */
  learnSpell?: string;
  /** Adventure XP the beat pays when it completes (source 'story'). [TUNE] */
  xp?: number;
}

/** The camera's move while a cutscene plays (story/cutscene.ts builds the track around the focus). */
export type CutsceneShot = 'push' | 'orbit' | 'wide';
export type CutsceneFocus = 'player' | 'partner' | 'boss' | 'spawn';

export interface CutsceneBeat extends BeatBase {
  kind: 'cutscene';
  lines: StoryLine[];
  shot?: CutsceneShot;
  focus?: CutsceneFocus;
  /** With focus 'spawn': the spawn the camera frames. */
  focusSpawn?: string;
  /** The first fusion (Chapter 1's finale): the party fuses when the cutscene's `fuse` beat fires. */
  fuse?: boolean;
}

export interface DialogueBeat extends BeatBase { kind: 'dialogue'; lines: StoryLine[] }

export type ObjectiveGoal =
  | { type: 'reach'; spawnId: string; radiusM: number }
  | { type: 'gate'; gateId: string };

export interface ObjectiveBeat extends BeatBase {
  kind: 'objective';
  /** What the HUD's objective line says (short; it is HUD, not a banner). */
  text: string;
  goal: ObjectiveGoal;
}

export interface FightBeat extends BeatBase { kind: 'fight'; text: string; encounterId: string }
export interface BossBeat extends BeatBase { kind: 'boss'; text: string; encounterId: string }

export interface TravelBeat extends BeatBase {
  kind: 'travel';
  text: string;
  to: { worldId: string; spawnId: string };
  /** 'gate': step through and arrive. 'flight': fly there (the party is fused for the trip; it ends on arrival). */
  via: 'gate' | 'flight';
  /** For 'flight': how close to the spawn counts as arrived. [TUNE] */
  radiusM?: number;
}

export interface ChoiceBeat extends BeatBase {
  kind: 'choice';
  /** The lines before the choice; the last one asks. */
  lines: StoryLine[];
  choices: StoryChoice[];
  /** The choice a skip (hold) takes. Default the first. */
  defaultChoice?: string;
}

export type StoryBeat = CutsceneBeat | DialogueBeat | ObjectiveBeat | FightBeat | BossBeat | TravelBeat | ChoiceBeat;

export interface StoryChapter {
  formatVersion: typeof STORY_FORMAT_VERSION;
  id: string;
  number: number;
  /** `[PLACEHOLDER] …` until the owner's chapter replaces it. */
  title: string;
  /** True until the chapter is adapted from the owner's book (Phase E). */
  placeholder: boolean;
  /** The world this chapter plays in (index.json maps it too; they must agree). */
  worldId: string;
  /** The manuscript file this chapter is adapted from (Phase E), e.g. `01-<slug>`. Absent on a placeholder. */
  manuscript?: string;
  beats: StoryBeat[];
}

export interface StoryCastMember { name: string }

export interface StoryIndexEntry {
  id: string;
  /** The chapter file under chapters/, without `.json`. */
  file: string;
  worldId: string;
  title: string;
}

export interface StoryIndex {
  formatVersion: typeof STORY_FORMAT_VERSION;
  /** True while any chapter is a placeholder. */
  placeholder: boolean;
  hub: { worldId: string; title: string };
  cast: Record<string, StoryCastMember>;
  chapters: StoryIndexEntry[];
}

/** A manuscript paragraph id set (Phase E's generated file, or none yet). */
export type ManuscriptIds = ReadonlySet<string>;

// ── Validators (authoring lint: an empty list = valid) ──────────────────────────────────────────────────────────

const ID = /^[a-z0-9][a-z0-9_.:-]*$/i;

export function linesOf(b: StoryBeat): readonly StoryLine[] {
  return b.kind === 'cutscene' || b.kind === 'dialogue' || b.kind === 'choice' ? b.lines : [];
}

/** Every line in the chapter, in order. */
export function chapterLines(c: StoryChapter): StoryLine[] {
  const out: StoryLine[] = [];
  for (const b of c.beats) out.push(...linesOf(b));
  return out;
}

/** The two placeholder marks: `placeholder: true` and a `[PLACEHOLDER]` title. */
export function placeholderMarks(c: Pick<StoryChapter, 'placeholder' | 'title'>): { flag: boolean; title: boolean } {
  return { flag: c.placeholder === true, title: typeof c.title === 'string' && c.title.startsWith(PLACEHOLDER_PREFIX) };
}

export interface ChapterContext {
  /** Cast ids index.json knows. */
  cast: ReadonlySet<string>;
  /** Worlds that exist (world specs), with their spawn ids, encounter ids and gate ids. */
  worlds: ReadonlyMap<string, { spawns: ReadonlySet<string>; encounters: ReadonlySet<string>; gates: ReadonlySet<string> }>;
  /** The manuscript this chapter is adapted from, when it exists (Phase E). Null = none. */
  manuscript: ManuscriptIds | null;
  /** Spell ids a beat may teach (A2's table), plus `partner.bolt`. */
  spells: ReadonlySet<string>;
}

export function validateChapter(c: StoryChapter, ctx: ChapterContext): string[] {
  const errs: string[] = [];
  const where = (s: string) => `${c?.id ?? '?'}: ${s}`;
  if (!c || typeof c !== 'object') return ['chapter: not an object'];
  if (c.formatVersion !== STORY_FORMAT_VERSION) errs.push(where(`formatVersion must be ${STORY_FORMAT_VERSION}`));
  if (typeof c.id !== 'string' || !ID.test(c.id)) errs.push(where('bad id'));
  if (!(Number.isInteger(c.number) && c.number >= 1)) errs.push(where('number must be a positive integer'));
  const marks = placeholderMarks(c);
  // a placeholder keeps BOTH marks; a chapter from the book keeps neither (and must trace to its manuscript)
  if (c.placeholder === true && !marks.title) errs.push(where(`a placeholder chapter's title must start ${PLACEHOLDER_PREFIX}`));
  if (c.placeholder !== true && marks.title) errs.push(where(`a ${PLACEHOLDER_PREFIX} title on a chapter marked placeholder: false`));
  if (typeof c.placeholder !== 'boolean') errs.push(where('placeholder must be true or false'));
  const world = ctx.worlds.get(c.worldId);
  if (!world) errs.push(where(`unknown world ${c.worldId}`));
  if (!Array.isArray(c.beats) || c.beats.length === 0) { errs.push(where('no beats')); return errs; }

  const beatIds = new Set<string>(), lineIds = new Set<string>();
  const spawnOk = (worldId: string, spawnId: string) => !!ctx.worlds.get(worldId)?.spawns.has(spawnId);
  const anyWorldHas = (k: 'encounters' | 'gates', id: string) => [...ctx.worlds.values()].some((w) => w[k].has(id));
  for (const b of c.beats) {
    const at = (s: string) => where(`${b?.id ?? '?'}: ${s}`);
    if (!b || typeof b.id !== 'string' || !ID.test(b.id)) { errs.push(where('a beat has a bad id')); continue; }
    if (beatIds.has(b.id)) errs.push(at('duplicate beat id'));
    beatIds.add(b.id);
    if (!(BEAT_KINDS as readonly string[]).includes(b.kind)) { errs.push(at(`unknown kind ${String(b.kind)}`)); continue; }
    if (b.checkpoint && !spawnOk(b.checkpoint.worldId, b.checkpoint.spawnId)) errs.push(at(`checkpoint ${b.checkpoint.worldId}/${b.checkpoint.spawnId} is no spawn`));
    if (b.learnSpell && !ctx.spells.has(b.learnSpell)) errs.push(at(`learns unknown spell ${b.learnSpell}`));
    if (b.xp !== undefined && !(Number.isFinite(b.xp) && b.xp >= 0 && b.xp <= 1000)) errs.push(at('xp must be 0..1000'));
    for (const l of linesOf(b)) {
      if (!l || typeof l.id !== 'string' || !ID.test(l.id)) { errs.push(at('a line has a bad id')); continue; }
      if (lineIds.has(l.id)) errs.push(at(`duplicate line id ${l.id}`));
      lineIds.add(l.id);
      if (typeof l.text !== 'string' || !l.text.trim()) errs.push(at(`${l.id}: empty text`));
      else if (l.text.length > 280) errs.push(at(`${l.id}: longer than 280 characters`));
      if (!(PARTY_SPEAKERS as readonly string[]).includes(l.speaker) && !ctx.cast.has(l.speaker)) errs.push(at(`${l.id}: unknown speaker ${l.speaker}`));
      if (l.sourceRef !== undefined) {
        if (!ctx.manuscript) errs.push(at(`${l.id}: sourceRef ${l.sourceRef} but the chapter has no manuscript`));
        else if (!ctx.manuscript.has(l.sourceRef)) errs.push(at(`${l.id}: sourceRef ${l.sourceRef} points at nothing`));
      }
    }
    switch (b.kind) {
      case 'cutscene': case 'dialogue':
        if (!b.lines?.length) errs.push(at('no lines'));
        if (b.kind === 'cutscene' && b.focus === 'spawn' && ![...ctx.worlds.values()].some((w) => w.spawns.has(b.focusSpawn ?? ''))) errs.push(at('focus spawn missing'));
        break;
      case 'choice': {
        if (!b.lines?.length) errs.push(at('no lines'));
        if (!b.choices || b.choices.length < 2) errs.push(at('a choice needs at least two options'));
        const ids = new Set((b.choices ?? []).map((x) => x.id));
        if (ids.size !== (b.choices ?? []).length) errs.push(at('duplicate choice id'));
        if (b.defaultChoice && !ids.has(b.defaultChoice)) errs.push(at(`default choice ${b.defaultChoice} is not an option`));
        break;
      }
      case 'objective':
        if (!b.text) errs.push(at('no objective text'));
        if (b.goal?.type === 'reach') {
          if (![...ctx.worlds.values()].some((w) => w.spawns.has(b.goal.type === 'reach' ? b.goal.spawnId : ''))) errs.push(at(`reach: unknown spawn ${b.goal.spawnId}`));
          if (!(b.goal.radiusM > 0)) errs.push(at('reach: radius must be > 0'));
        } else if (b.goal?.type === 'gate') {
          if (!anyWorldHas('gates', b.goal.gateId)) errs.push(at(`gate: unknown gate ${b.goal.gateId}`));
        } else errs.push(at('unknown goal'));
        break;
      case 'fight': case 'boss':
        if (!anyWorldHas('encounters', b.encounterId)) errs.push(at(`unknown encounter ${b.encounterId}`));
        break;
      case 'travel':
        if (!spawnOk(b.to?.worldId, b.to?.spawnId)) errs.push(at(`travel to ${b.to?.worldId}/${b.to?.spawnId}: no such spawn`));
        if (b.via !== 'gate' && b.via !== 'flight') errs.push(at('via must be gate or flight'));
        if (b.via === 'flight' && !(b.radiusM && b.radiusM > 0)) errs.push(at('a flight travel needs radiusM'));
        break;
    }
  }
  // "true to the owner" is checkable: a chapter from the book with no sourceRef at all fails
  if (c.placeholder === false) {
    if (!c.manuscript) errs.push(where('a chapter from the book must name its manuscript'));
    if (!chapterLines(c).some((l) => l.sourceRef)) errs.push(where('a chapter from the book has no sourceRef on any line'));
  }
  return errs;
}

export function validateStoryIndex(ix: StoryIndex, chapters: ReadonlyMap<string, StoryChapter>, worlds: ReadonlySet<string>): string[] {
  const errs: string[] = [];
  if (ix.formatVersion !== STORY_FORMAT_VERSION) errs.push(`index: formatVersion must be ${STORY_FORMAT_VERSION}`);
  if (!worlds.has(ix.hub?.worldId)) errs.push(`index: unknown hub world ${ix.hub?.worldId}`);
  if (!ix.chapters?.length) errs.push('index: no chapters');
  const seen = new Set<string>();
  let anyPlaceholder = false;
  for (const e of ix.chapters ?? []) {
    if (seen.has(e.id)) errs.push(`index: duplicate chapter ${e.id}`);
    seen.add(e.id);
    const c = chapters.get(e.id);
    if (!c) { errs.push(`index: chapter ${e.id} has no file`); continue; }
    if (c.worldId !== e.worldId) errs.push(`index: ${e.id} maps to ${e.worldId} but the chapter plays in ${c.worldId}`);
    if (c.title !== e.title) errs.push(`index: ${e.id}'s title differs from the chapter's`);
    if (!worlds.has(e.worldId)) errs.push(`index: ${e.id} maps to unknown world ${e.worldId}`);
    if (c.placeholder) anyPlaceholder = true;
  }
  if (anyPlaceholder && ix.placeholder !== true) errs.push('index: a placeholder chapter is listed but the index is not marked placeholder');
  for (const [k, v] of Object.entries(ix.cast ?? {})) {
    if (!v?.name?.startsWith(PLACEHOLDER_PREFIX) && ix.placeholder) errs.push(`index: cast ${k}'s name must stay ${PLACEHOLDER_PREFIX} until the owner names it`);
  }
  return errs;
}

/** The speaker's name without the placeholder prefix (the dialogue box shows the PLACEHOLDER tag instead). */
export function displayName(name: string): string {
  return name.startsWith(PLACEHOLDER_PREFIX) ? name.slice(PLACEHOLDER_PREFIX.length).trim() : name;
}
