// Authoritative registry of all 3D maps in FEL.
// Each entry maps to a Meshy-derived GLB in public/models/maps/.
// Scale converts the normalized [-1,1] GLB bounds to real-world metres.

export interface MapConfig {
  key: string;
  label: string;
  glb: string;            // path under public/
  scale: number;          // uniform scale to apply
  spawnPos: [number, number, number]; // player start (world coords after scale)
  spawnYaw: number;       // initial facing (radians, 0=+Z)
  camOffset: [number, number, number]; // follow-cam offset from player
  ambientColor: string;   // tint for hemisphere light
  fogColor: string;       // scene fog colour
  fogNear: number;
  fogFar: number;
  floorY: number;         // ground plane Y in world coords (after scale)
  ceilingY: number;       // approx ceiling for cam collision
  boundsMin: [number, number, number]; // navigable AABB min
  boundsMax: [number, number, number]; // navigable AABB max
  backdrop?: string;      // photographic sky/environment backdrop shown behind the map
  mapOffset?: [number, number, number]; // world translation applied to the loaded map mesh (after scale+rotation)
  mapRotationY?: number;  // Y-axis rotation (radians) applied to the loaded map mesh, e.g. to align a painted hoop under the functional rim
  matteFloor?: boolean;   // M12.2: treat the surface as matte painted blacktop (kills specular/reflection sheen that made the blue court read as water) and brightens albedo
}

export const MAPS: Record<string, MapConfig> = {
  'venice-blacktop': {
    key: 'venice-blacktop',
    label: 'Venice Blacktop Court',
    glb: '/models/maps/venice-blacktop.glb',
    scale: 14,
    spawnPos: [0, 0, 6],
    spawnYaw: Math.PI,
    camOffset: [-3, 4, 8],
    ambientColor: '#3a4a5e',
    fogColor: '#9fc0d8',
    fogNear: 34,
    fogFar: 95,
    floorY: 0,
    ceilingY: 8,
    boundsMin: [-13, 0, -13],
    boundsMax: [13, 8, 13],
    backdrop: '/backdrops/venice-sky-day.jpg',
  },
  'shop': {
    key: 'shop',
    label: 'Venice Ball Shop',
    glb: '/models/maps/shop.glb',
    scale: 6,
    spawnPos: [0, 0, 2],
    spawnYaw: 0,
    camOffset: [-2, 3, 5],
    ambientColor: '#1e1412',
    fogColor: '#0c0808',
    fogNear: 8,
    fogFar: 25,
    floorY: 0,
    ceilingY: 6,
    boundsMin: [-5, 0, -5],
    boundsMax: [5, 6, 5],
  },
  'venice-blue-court': {
    key: 'venice-blue-court',
    label: 'Venice Blue Court',
    glb: '/models/maps/venice-blue-court.glb',
    scale: 14,
    spawnPos: [0, 0, 6],
    spawnYaw: Math.PI,
    camOffset: [-3, 4, 8],
    ambientColor: '#3a2c3e',
    fogColor: '#5a4258',
    fogNear: 32,
    fogFar: 90,
    floorY: 0,
    ceilingY: 8,
    boundsMin: [-13, 0, -13],
    boundsMax: [13, 8, 13],
    backdrop: '/backdrops/venice-sky-sunset.jpg',
    // Rotate the scanned court 90deg and slide it +Z so one painted baseline hoop
    // sits directly under the functional rim at world origin (0, 3.05, 0),
    // instead of the rim floating over the mid-court centre graphic.
    mapRotationY: Math.PI / 2,
    mapOffset: [0, 0, 11],
    // M12.2(b): the scanned surface is a glossy blue that read as rippling water under
    // the neon rig. Force a matte, brightened blacktop look so it reads as a painted court.
    matteFloor: true,
  },
  'venice-skatepark': {
    key: 'venice-skatepark',
    label: 'Venice Beach Skatepark',
    glb: '/models/maps/venice-skatepark.glb',
    scale: 14,
    spawnPos: [0, 0, 10],
    spawnYaw: Math.PI,
    camOffset: [-3.5, 4.5, 9],
    ambientColor: '#3a4a5e',
    fogColor: '#9fc0d8',
    fogNear: 34,
    fogFar: 95,
    floorY: 0,
    ceilingY: 9,
    boundsMin: [-13, 0, -13],
    boundsMax: [13, 9, 13],
    backdrop: '/backdrops/venice-sky-day.jpg',
  },
  'dojo': {
    key: 'dojo',
    label: 'Shimogamo Dojo',
    glb: '/models/maps/dojo.glb',
    scale: 8,
    spawnPos: [0, 0, 3],
    spawnYaw: Math.PI,
    camOffset: [-2, 3.5, 6],
    ambientColor: '#1a1412',
    fogColor: '#1a1210',
    fogNear: 16,
    fogFar: 52,
    floorY: 0,
    ceilingY: 10,
    boundsMin: [-7, 0, -6],
    boundsMax: [7, 10, 6],
    backdrop: '/backdrops/karate.jpg',
  },
  'tennis-court': {
    key: 'tennis-court',
    label: 'Venice Tennis Court',
    glb: '/models/maps/tennis-court.glb',
    scale: 10,
    spawnPos: [0, 0, 4],
    spawnYaw: Math.PI,
    camOffset: [-3, 4, 7],
    ambientColor: '#3a4a5e',
    fogColor: '#0e1116',
    fogNear: 20,
    fogFar: 120,
    floorY: 0,
    ceilingY: 8,
    boundsMin: [-12, 0, -12],
    boundsMax: [12, 8, 12],
    backdrop: '/backdrops/venice-sky-day.jpg',
  },
  'coastal-links': {
    key: 'coastal-links',
    label: 'Coastal Links',
    glb: '/models/maps/coastal-links.glb',
    scale: 12,
    spawnPos: [0, 0, 6],
    spawnYaw: Math.PI,
    camOffset: [-4, 5, 9],
    ambientColor: '#4a5e3a',
    fogColor: '#0e1116',
    fogNear: 30,
    fogFar: 160,
    floorY: 0,
    ceilingY: 10,
    boundsMin: [-15, 0, -15],
    boundsMax: [15, 10, 15],
    backdrop: '/backdrops/venice-sky-day.jpg',
  },
  'baseball-park': {
    key: 'baseball-park',
    label: 'Catalina Ballpark',
    glb: '/models/maps/baseball-park.glb',
    scale: 12,
    spawnPos: [0, 0, 6],
    spawnYaw: Math.PI,
    camOffset: [-4, 5, 9],
    ambientColor: '#3a4a5e',
    fogColor: '#0e1116',
    fogNear: 30,
    fogFar: 160,
    floorY: 0,
    ceilingY: 10,
    boundsMin: [-15, 0, -15],
    boundsMax: [15, 10, 15],
    backdrop: '/backdrops/venice-sky-day.jpg',
  },
  'gridiron': {
    key: 'gridiron',
    label: 'Gridiron Stadium',
    glb: '/models/maps/gridiron.glb',
    scale: 14,
    spawnPos: [0, 0, 6],
    spawnYaw: Math.PI,
    camOffset: [-4, 5, 9],
    ambientColor: '#3a4a5e',
    fogColor: '#0e1116',
    fogNear: 30,
    fogFar: 160,
    floorY: 0,
    ceilingY: 10,
    boundsMin: [-16, 0, -16],
    boundsMax: [16, 10, 16],
    backdrop: '/backdrops/venice-sky-sunset.jpg',
  },
  'soccer-stadium': {
    key: 'soccer-stadium',
    label: 'Coastal FC Stadium',
    glb: '/models/maps/soccer-stadium.glb',
    scale: 14,
    spawnPos: [0, 0, 6],
    spawnYaw: Math.PI,
    camOffset: [-4, 5, 9],
    ambientColor: '#3a4a5e',
    fogColor: '#0e1116',
    fogNear: 30,
    fogFar: 160,
    floorY: 0,
    ceilingY: 10,
    boundsMin: [-16, 0, -16],
    boundsMax: [16, 10, 16],
    backdrop: '/backdrops/venice-sky-day.jpg',
  },
  'sand-court': {
    key: 'sand-court',
    label: 'Venice Sand Court',
    glb: '/models/maps/sand-court.glb',
    scale: 10,
    spawnPos: [0, 0, 4],
    spawnYaw: Math.PI,
    camOffset: [-3, 4, 7],
    ambientColor: '#5e4a3a',
    fogColor: '#0e1116',
    fogNear: 20,
    fogFar: 120,
    floorY: 0,
    ceilingY: 8,
    boundsMin: [-10, 0, -10],
    boundsMax: [10, 8, 10],
    backdrop: '/backdrops/venice-sky-sunset.jpg',
  },
  'surf-break': {
    key: 'surf-break',
    label: 'Surf Break',
    glb: '/models/maps/surf-break.glb',
    scale: 12,
    spawnPos: [0, 0, 4],
    spawnYaw: Math.PI,
    camOffset: [-3.5, 4.5, 8],
    ambientColor: '#2a4a5e',
    fogColor: '#0a1a22',
    fogNear: 25,
    fogFar: 140,
    floorY: 0,
    ceilingY: 8,
    boundsMin: [-12, 0, -12],
    boundsMax: [12, 8, 12],
    backdrop: '/backdrops/venice-sky-sunset.jpg',
  },
  'mountain-slope': {
    key: 'mountain-slope',
    label: 'Mountain Slope',
    glb: '/models/maps/mountain-slope.glb',
    scale: 14,
    spawnPos: [0, 0, 4],
    spawnYaw: Math.PI,
    camOffset: [-4, 5, 9],
    ambientColor: '#8a9ab0',
    fogColor: '#dfe8f0',
    fogNear: 25,
    fogFar: 140,
    floorY: 0,
    ceilingY: 12,
    boundsMin: [-14, 0, -14],
    boundsMax: [14, 12, 14],
    backdrop: '/backdrops/venice-sky-day.jpg',
  },
  'gymnastics-gym': {
    key: 'gymnastics-gym',
    label: 'Pacifica Gymnastics',
    glb: '/models/maps/gymnastics-gym.glb',
    scale: 8,
    spawnPos: [0, 0, 3],
    spawnYaw: Math.PI,
    camOffset: [-2, 3.5, 6],
    ambientColor: '#3a3a5e',
    fogColor: '#0e1116',
    fogNear: 15,
    fogFar: 90,
    floorY: 0,
    ceilingY: 8,
    boundsMin: [-8, 0, -8],
    boundsMax: [8, 8, 8],
    backdrop: '/backdrops/venice-sky-day.jpg',
  },
  'neuro-arena': {
    key: 'neuro-arena',
    label: 'NeuroArena',
    glb: '/models/maps/neuro-arena.glb',
    scale: 8,
    spawnPos: [0, 0, 3],
    spawnYaw: Math.PI,
    camOffset: [-2, 3.5, 6],
    ambientColor: '#1a1a3e',
    fogColor: '#0a0d14',
    fogNear: 15,
    fogFar: 90,
    floorY: 0,
    ceilingY: 8,
    boundsMin: [-8, 0, -8],
    boundsMax: [8, 8, 8],
    backdrop: '/backdrops/venice-sky-sunset.jpg',
  },
};

// Lookup helpers
export function getMap(key: string): MapConfig | undefined {
  return MAPS[key];
}

export function getMapKeys(): string[] {
  return Object.keys(MAPS);
}