import { describe, expect, it } from 'vitest';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { DOORS } from './doors';
import { TABS } from '../../components/shell/tab-bar';
import { FAMILIES, OFF_SHELF } from './families';
import { MODE_INFO } from '../game-data';

/**
 * The orphan test.
 *
 * Deleting the old five-tab bar took the only link to nine working routes with it — /camp, /education, /live,
 * /workout, /cards, /market and friends. Nobody noticed, because an orphaned page does not break; it just goes
 * quiet, and a feature nobody can click is a feature nobody has. That happened once and the fix was a list; this
 * is what stops it happening a second time.
 *
 * It walks the real app directory, collects every route with a page, and fails if nothing anywhere in
 * app/, components/ or lib/ points at it.
 */

const ROOT = join(__dirname, '..', '..');

/** Routes that are reached by something other than a link, and why. */
const NOT_NAVIGABLE: Record<string, string> = {
  '/login': 'where an unauthenticated request is redirected',
  '/signup': 'reached from /login and from a scanned card',
  '/dev': 'developer views, deliberately unlisted',
  '/c': 'a scanned creator card, entered by its code',
  '/card': "somebody else's creator card, opened from a shared link or a QR code",
  '/p': 'a public profile, entered by its handle',
  '/elijah': 'Elijah\'s links page, opened from his social profiles (link in bio), not from inside the app',
  '/controller': 'joined by code from a phone, never by a link on the phone',
  '/admin': 'shown in the rail to an admin only',
  '/game-surface.css': 'not a route',
  '/play': 'a tab',
  '/train': 'a tab',
  '/profile': 'a tab',
  '/studio': 'HOLD — not shipped, deliberately unlinked',
  '/settings': 'alias of /account; app/settings/page.tsx redirects there, and the consent screen links /account',
  '/coach/join/[token]': 'private coach invite link, generated by lib/coach/invite.ts and shared outside the app',
  '/consent/guardian/[token]': 'private guardian-consent link, generated for a guardian or player handoff',
  '/screen/program/[lane]': 'Quick Screen result lane, generated from lib/screen/routes.ts and sessionStorage state',
};

function appRoutes(): string[] {
  const out = new Set<string>();
  const appRoot = join(ROOT, 'app');
  const walk = (dir: string) => {
    for (const e of readdirSync(dir)) {
      if (e === 'api') continue;
      const p = join(dir, e);
      if (statSync(p).isDirectory()) { walk(p); continue; }
      if (!e.startsWith('page.')) continue;
      const rel = dir.slice(appRoot.length).replace(/\\/g, '/');
      const parts = rel.split('/').filter((part) => part && !part.startsWith('_') && !part.startsWith('('));
      const route = parts.length ? `/${parts.join('/')}` : '/';
      if (route !== '/') out.add(route);
    }
  };
  walk(appRoot);
  return [...out].sort();
}

function addTarget(hrefs: Set<string>, raw: string) {
  if (!raw.startsWith('/')) return;
  hrefs.add(raw.replace(/\$\{[^}]+\}/g, '[dynamic]'));
}

function routeReachedBy(route: string, href: string): boolean {
  const path = href.split('?')[0];
  const routeParts = route.split('/').filter(Boolean);
  const hrefParts = path.split('/').filter(Boolean);
  if (hrefParts.length < routeParts.length) return false;
  for (let i = 0; i < routeParts.length; i += 1) {
    const routePart = routeParts[i];
    const hrefPart = hrefParts[i];
    if (routePart.startsWith('[') && routePart.endsWith(']')) continue;
    if (hrefPart.startsWith('[') && hrefPart.endsWith(']')) continue;
    if (routePart !== hrefPart) return false;
  }
  return true;
}

function hasExplicitExcuse(route: string): boolean {
  if (route in NOT_NAVIGABLE) return true;
  return Object.keys(NOT_NAVIGABLE).some((r) => route.startsWith(r + '/'));
}

function everyLinkTarget(): Set<string> {
  const hrefs = new Set<string>();
  const scan = (dir: string) => {
    for (const e of readdirSync(dir)) {
      if (e === 'node_modules' || e.startsWith('.')) continue;
      const p = join(dir, e);
      if (statSync(p).isDirectory()) { scan(p); continue; }
      if (!/\.(tsx|ts)$/.test(p) || p.endsWith('.test.ts') || p.endsWith('.test.tsx')) continue;
      const src = readFileSync(p, 'utf8');
      for (const m of src.matchAll(/href=["'`](\/[A-Za-z0-9/[\]._-]*)/g)) addTarget(hrefs, m[1]);
      // A card grid holds its links in data — `href: '/closet'` — not in JSX, and those count just as much.
      for (const m of src.matchAll(/href:\s*["'`](\/[A-Za-z0-9/[\]._-]*)/g)) addTarget(hrefs, m[1]);
      for (const m of src.matchAll(/(?:push|replace|redirect)\(\s*["'`](\/[A-Za-z0-9/[\]._-]*)/g)) addTarget(hrefs, m[1]);
      for (const m of src.matchAll(/href=\{\s*`([^`]+)`\s*\}/g)) addTarget(hrefs, m[1]);
      for (const m of src.matchAll(/`(\/[^`]*\$\{[^`]+)`/g)) addTarget(hrefs, m[1]);
    }
  };
  scan(join(ROOT, 'app'));
  scan(join(ROOT, 'components'));
  scan(join(ROOT, 'lib'));
  // Links the shell builds from data rather than writing literally.
  for (const t of TABS) hrefs.add(t.href);
  for (const d of DOORS) hrefs.add(d.href);
  for (const f of FAMILIES) for (const m of f.modes) {
    const href = MODE_INFO[m as keyof typeof MODE_INFO]?.href;
    if (href) hrefs.add(href);
  }
  for (const k of Object.keys(OFF_SHELF)) hrefs.add('/play/' + k);
  return hrefs;
}

describe('nothing in the app is orphaned', () => {
  const routes = appRoutes();
  const hrefs = everyLinkTarget();
  const reached = (r: string) => [...hrefs].some((h) => routeReachedBy(r, h));

  it('found a real app directory to walk', () => {
    expect(routes.length).toBeGreaterThan(20);
  });

  it('every page route is either linked or listed as not navigable, with a reason', () => {
    const orphans = routes.filter((r) => !reached(r) && !hasExplicitExcuse(r));
    expect(orphans, `nothing links to these — give each a home in lib/nav/doors.ts or a reason in NOT_NAVIGABLE`)
      .toEqual([]);
  });

  it('the athlete creator is linked, not only the /creator hub above it', () => {
    // HOTFIX (2026-09-24): the walk above sees top-level routes only, and /creator is linked -- so /creator/athlete
    // shipped with nothing pointing at it while this file stayed green. Its door is on Profile.
    expect(hrefs.has('/creator/athlete')).toBe(true);
  });

  it('the not-navigable list has not gone stale', () => {
    // A route that was excused and then deleted leaves a lie behind in the list.
    const gone = Object.keys(NOT_NAVIGABLE)
      .filter((r) => r.startsWith('/') && !r.includes('.'))
      .filter((r) => !routes.includes(r) && !routes.some((route) => route.startsWith(r + '/')));
    expect(gone, 'these are excused but no longer exist').toEqual([]);
  });
});

describe('the doors', () => {
  it('sends every door to a route that exists', () => {
    const routes = appRoutes();
    for (const d of DOORS) expect(routes.some((r) => routeReachedBy(r, d.href)), d.href).toBe(true);
  });

  it('lists no door twice', () => {
    expect(new Set(DOORS.map((d) => d.href)).size).toBe(DOORS.length);
  });

  it('gives every tab some depth', () => {
    for (const t of TABS) expect(DOORS.filter((d) => d.tab === t.id).length, t.id).toBeGreaterThan(2);
  });
});
