/**
 * Coach Feature Stub Interfaces — v1
 *
 * These interfaces define the contracts for future AI-powered coach features.
 * In v1, all implementations are stubs or manual-only workflows.
 *
 * EU AI Act Note: Any future synthetic voice/likeness or AI-generated
 * coaching content MUST include clear disclosure that it is AI-generated.
 */

/* ────────── Synthetic Coach Provider ────────── */

export interface SyntheticCoachConfig {
  /** The person whose likeness is being synthesized */
  identity: 'elijah_bonds';
  /** Voice model identifier (future) */
  voiceModelId?: string;
  /** Avatar/mesh model identifier (future) */
  avatarModelId?: string;
  /** Whether to show AI disclosure overlay */
  showAiDisclosure: boolean;
}

export interface SyntheticCoachOutput {
  /** Type of output */
  type: 'audio' | 'video' | 'avatar';
  /** URL to the generated media asset */
  mediaUrl: string;
  /** Duration in seconds */
  durationSec: number;
  /** AI disclosure text to display */
  disclosureText: string;
}

/**
 * SyntheticCoachProvider — generates AI voice/likeness of Coach Bonds.
 *
 * v1 status: STUB — returns null. Real recorded Elijah only in v1.
 * Future: Will connect to voice cloning + avatar generation APIs.
 */
export interface ISyntheticCoachProvider {
  /** Check if the provider is available and configured */
  isAvailable(): Promise<boolean>;
  /** Generate a spoken coaching cue */
  generateSpokenCue(text: string, config: SyntheticCoachConfig): Promise<SyntheticCoachOutput | null>;
  /** Generate a video demonstration overlay */
  generateDemoOverlay(exerciseSlug: string, config: SyntheticCoachConfig): Promise<SyntheticCoachOutput | null>;
}

/** v1 stub implementation */
export class StubSyntheticCoachProvider implements ISyntheticCoachProvider {
  async isAvailable(): Promise<boolean> {
    return false;
  }
  async generateSpokenCue(): Promise<SyntheticCoachOutput | null> {
    console.log('[SyntheticCoach] Stub — not available in v1');
    return null;
  }
  async generateDemoOverlay(): Promise<SyntheticCoachOutput | null> {
    console.log('[SyntheticCoach] Stub — not available in v1');
    return null;
  }
}

/* ────────── AI Form Analysis ────────── */

export interface FormAnalysisFrame {
  /** Timestamp in the video (seconds) */
  timestamp: number;
  /** Detected joint positions (normalized 0-1) */
  joints: Record<string, { x: number; y: number; confidence: number }>;
}

export interface FormAnalysisResult {
  /** Overall form quality score (0-100) */
  overallScore: number;
  /** Per-frame analysis */
  frames: FormAnalysisFrame[];
  /** Text feedback from the analysis */
  feedback: string[];
  /** Specific issues detected */
  issues: { severity: 'info' | 'warning' | 'critical'; description: string; timestamp?: number }[];
  /** AI disclosure */
  disclosureText: string;
}

/**
 * IAIFormAnalysis — analyzes user-recorded exercise videos for form quality.
 *
 * v1 status: STUB — returns null. Manual side-by-side comparison only.
 * Future: Will use pose estimation (MediaPipe/MoveNet) + LLM analysis.
 */
export interface IAIFormAnalysis {
  /** Check if AI analysis is available */
  isAvailable(): Promise<boolean>;
  /** Analyze a video for exercise form */
  analyzeForm(videoUrl: string, exerciseSlug: string): Promise<FormAnalysisResult | null>;
  /** Get supported exercises for AI analysis */
  getSupportedExercises(): Promise<string[]>;
}

/** v1 stub implementation */
export class StubAIFormAnalysis implements IAIFormAnalysis {
  async isAvailable(): Promise<boolean> {
    return false;
  }
  async analyzeForm(): Promise<FormAnalysisResult | null> {
    console.log('[AIFormAnalysis] Stub — not available in v1');
    return null;
  }
  async getSupportedExercises(): Promise<string[]> {
    return [];
  }
}

/* ────────── EU AI Act Disclosure Utilities ────────── */

export const AI_DISCLOSURE_TEXT = 'This content was generated using artificial intelligence and does not represent a real recording of Coach Elijah Bonds.';

export function getAiDisclosureForType(type: SyntheticCoachOutput['type']): string {
  switch (type) {
    case 'audio':
      return 'This voice was generated by AI. It is not a real recording.';
    case 'video':
      return 'This video contains AI-generated content. It is not a real recording of Coach Elijah Bonds.';
    case 'avatar':
      return 'This avatar is AI-generated and does not represent a real-time recording.';
    default:
      return AI_DISCLOSURE_TEXT;
  }
}
