// export-skins — the MPFB2 (MakeHuman) CC0 skin set → web-sized maps for the
// hero's `skin` material (ship pass 3, rung 2). All MakeHuman skins share the
// basemesh UV layout, so any of them fits the forge body, and one skin's normal
// map serves as the shared DETAIL normal for all of them.
//
//   npx tsx scripts/avatar/skins/export-skins.mts [--size 2048] [--quality 85]
// Source: ~/Library/Application Support/Blender/5.1/extensions/.user/user_default/mpfb/data/skins
import sharp from 'sharp';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const flag = (n: string, d: string) => { const i = process.argv.indexOf(`--${n}`); return i > 0 ? process.argv[i + 1] : d; };
const SIZE = Number(flag('size', '2048')), Q = Number(flag('quality', '85'));
// --suffix -1024: write a second, smaller set beside the shipped one (`<key>-1024.jpg`, `detail-normal-1024.jpg`)
// for the mobile quality tier; the manifest and lib/babylon/core/skinLibrary.ts describe the base set only.
const SUFFIX = flag('suffix', '');
const SRC = join(process.env.HOME!, 'Library/Application Support/Blender/5.1/extensions/.user/user_default/mpfb/data/skins');
const OUT = 'public/models/skins';

interface Skin { key: string; dir: string; family: 'dark' | 'medium' | 'light'; sex: 'male' | 'female'; age: 'young' | 'middle' }
const SKINS: Skin[] = [
  { key: 'dark-male',    dir: 'middleage_african_male',    family: 'dark',   sex: 'male',   age: 'middle' },
  { key: 'dark-female',  dir: 'middleage_african_female',  family: 'dark',   sex: 'female', age: 'middle' },
  { key: 'medium-male',  dir: 'middleage_asian_male',      family: 'medium', sex: 'male',   age: 'middle' },
  { key: 'medium-female',dir: 'middleage_asian_female',    family: 'medium', sex: 'female', age: 'middle' },
  { key: 'light-male',   dir: 'middleage_caucasian_male',  family: 'light',  sex: 'male',   age: 'middle' },
  { key: 'light-female', dir: 'young_caucasian_female',    family: 'light',  sex: 'female', age: 'young' },
];
const DETAIL_NORMAL = { dir: 'mindfront_skin_male_african_middleage', key: 'normalmapTexture' };

function mhmat(dir: string): Record<string, string> {
  const files = readFileSync(join(SRC, dir, dir + '.mhmat'), 'utf8').split('\n');
  const out: Record<string, string> = {};
  for (const l of files) { const m = /^(\w+)\s+(.+)$/.exec(l.trim()); if (m) out[m[1]] = m[2].trim(); }
  return out;
}
async function meanRGB(file: string): Promise<[number, number, number]> {
  const { channels } = await sharp(file).resize(64, 64, { fit: 'fill' }).stats();
  return [channels[0].mean, channels[1].mean, channels[2].mean].map(Math.round) as [number, number, number];
}

mkdirSync(OUT, { recursive: true });
const manifest: Record<string, unknown>[] = [];
for (const s of SKINS) {
  const m = mhmat(s.dir); const src = join(SRC, s.dir, m.diffuseTexture);
  if (!existsSync(src)) { console.warn('missing', src); continue; }
  const out = join(OUT, `${s.key}${SUFFIX}.jpg`);
  const info = await sharp(src).resize(SIZE, SIZE, { fit: 'fill' }).jpeg({ quality: Q, mozjpeg: true }).toFile(out);
  const rgb = await meanRGB(src);
  const tint = (m.diffuseColor ?? '1 1 1').split(/\s+/).map(Number);
  manifest.push({ key: s.key, family: s.family, sex: s.sex, age: s.age, albedo: `/models/skins/${s.key}.jpg`, meanRGB: rgb, diffuseColor: tint, source: `mpfb/data/skins/${s.dir}`, licence: 'CC0 (MakeHuman community assets)' });
  console.log(`${s.key.padEnd(14)} ${(info.size / 1024).toFixed(0).padStart(5)} KB  mean rgb ${rgb.join(',')}  ← ${m.diffuseTexture}`);
}
{
  const m = mhmat(DETAIL_NORMAL.dir); const src = join(SRC, DETAIL_NORMAL.dir, m[DETAIL_NORMAL.key]);
  const out = join(OUT, `detail-normal${SUFFIX}.jpg`);
  const info = await sharp(src).resize(SIZE, SIZE, { fit: 'fill' }).jpeg({ quality: 90, mozjpeg: true }).toFile(out);
  console.log(`detail-normal  ${(info.size / 1024).toFixed(0).padStart(5)} KB  ← ${DETAIL_NORMAL.dir}/${m[DETAIL_NORMAL.key]}`);
}
if (SUFFIX) { console.log(`suffix ${SUFFIX}: ${manifest.length} skins + detail normal at ${SIZE}px written; manifest and skinLibrary.ts untouched`); process.exit(0); }
writeFileSync(join(OUT, 'manifest.json'), JSON.stringify({ generated: new Date().toISOString().slice(0, 10), size: SIZE, detailNormal: '/models/skins/detail-normal.jpg', skins: manifest }, null, 2));
// A generated constant so the runtime can pick a skin synchronously inside applyIdentity.
const ts = `// GENERATED by scripts/avatar/skins/export-skins.mts — edit the script, not this file.
// The MPFB2 (MakeHuman, CC0) skin set as web maps under public/models/skins (ship pass 3, rung 2).
export type SkinFamily = 'dark' | 'medium' | 'light';
export interface SkinEntry { key: string; family: SkinFamily; sex: 'male' | 'female'; albedo: string; meanRGB: [number, number, number] }
export const SKIN_DETAIL_NORMAL = '/models/skins/detail-normal.jpg';
export const SKIN_LIBRARY: SkinEntry[] = ${JSON.stringify(manifest.map((m) => ({ key: m.key, family: m.family, sex: m.sex, albedo: m.albedo, meanRGB: m.meanRGB })), null, 2)};
`;
writeFileSync('lib/babylon/core/skinLibrary.ts', ts);
console.log(`manifest: ${manifest.length} skins → ${OUT}/manifest.json and lib/babylon/core/skinLibrary.ts`);
