#!/usr/bin/env bash
#
# Final Evolution Lab — local development bring-up (macOS / Linux).
#
# Run from the FEL-full-app directory, which is where the Next.js app lives on
# this branch:
#
#   cd FEL-full-app && ./scripts/dev-setup.sh
#
# Brings up Postgres, writes .env, installs dependencies, pushes the schema,
# and verifies the running server can actually reach the database. Safe to
# re-run: an existing .env and an existing database are left alone.
#
# The sign-in outage this guards against came from DATABASE_URL pointing at a
# loopback address in an environment with no Postgres on it. The final step
# here checks reachability rather than assuming it.

set -euo pipefail

PORT="${FEL_PORT:-3000}"
DB_PORT="${FEL_DB_PORT:-5432}"
DB_NAME="${FEL_DB_NAME:-fel}"
DB_USER="${FEL_DB_USER:-felapp}"
DB_PASS="${FEL_DB_PASS:-felapp}"
CONTAINER="${FEL_PG_CONTAINER:-fel-postgres}"

cd "$(dirname "$0")/.."
ROOT="$(pwd)"

say()  { printf '\n\033[1;36m==> %s\033[0m\n' "$1"; }
ok()   { printf '    \033[0;32m✓\033[0m %s\n' "$1"; }
warn() { printf '    \033[0;33m!\033[0m %s\n' "$1"; }
die()  { printf '\n\033[0;31m✗ %s\033[0m\n' "$1" >&2; exit 1; }

# --- 1. Postgres -----------------------------------------------------------
# Docker first: it keeps the database isolated and disposable. Falls back to a
# Homebrew server, then to any Postgres already listening on the port.
say "Postgres"
DB_HOST=127.0.0.1

if docker info >/dev/null 2>&1; then
  if docker ps -a --format '{{.Names}}' | grep -qx "$CONTAINER"; then
    docker start "$CONTAINER" >/dev/null 2>&1 || true
    ok "reusing container '$CONTAINER'"
  else
    docker run -d --name "$CONTAINER" \
      -e POSTGRES_USER="$DB_USER" \
      -e POSTGRES_PASSWORD="$DB_PASS" \
      -e POSTGRES_DB="$DB_NAME" \
      -p "${DB_PORT}:5432" \
      postgres:16 >/dev/null
    ok "started container '$CONTAINER' on port $DB_PORT"
  fi
  printf '    waiting for Postgres'
  for _ in $(seq 1 45); do
    if docker exec "$CONTAINER" pg_isready -U "$DB_USER" >/dev/null 2>&1; then
      printf '\n'; ok "accepting connections"; break
    fi
    printf '.'; sleep 1
  done
  docker exec "$CONTAINER" pg_isready -U "$DB_USER" >/dev/null 2>&1 \
    || die "Postgres did not become ready. Check: docker logs $CONTAINER"

elif command -v brew >/dev/null 2>&1 && brew list 2>/dev/null | grep -q '^postgresql@'; then
  FORMULA="$(brew list | grep '^postgresql@' | head -1)"
  brew services start "$FORMULA" >/dev/null 2>&1 || true
  ok "started $FORMULA via brew services"
  sleep 3
  createuser -h "$DB_HOST" -p "$DB_PORT" -s "$DB_USER" 2>/dev/null || true
  createdb  -h "$DB_HOST" -p "$DB_PORT" -O "$DB_USER" "$DB_NAME" 2>/dev/null || true
  DB_PASS=""   # local trust auth
  ok "database '$DB_NAME' ready"

elif command -v pg_isready >/dev/null 2>&1 && pg_isready -h "$DB_HOST" -p "$DB_PORT" >/dev/null 2>&1; then
  warn "using the Postgres already listening on ${DB_HOST}:${DB_PORT}"
  # Pre-existing server: its roles and auth are not ours to assume. Try as the
  # configured role, then as the shell user, and let the verify step below be
  # the judge rather than guessing a password here.
  createdb -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" "$DB_NAME" 2>/dev/null \
    || createdb -h "$DB_HOST" -p "$DB_PORT" "$DB_NAME" 2>/dev/null \
    || true
  if psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -tAc 'SELECT 1' >/dev/null 2>&1; then
    DB_PASS=""   # reachable without a password on this server
  fi

else
  die "No Postgres available.
    Install Docker Desktop, or:  brew install postgresql@16 && brew services start postgresql@16
    Then re-run this script."
fi

if [ -n "$DB_PASS" ]; then
  DB_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"
else
  DB_URL="postgresql://${DB_USER}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"
fi

# --- 2. .env ---------------------------------------------------------------
say "Environment"
if [ -f .env ]; then
  ok ".env already exists — leaving it untouched"
  if grep -qE '^DATABASE_URL=.*(127\.0\.0\.1|localhost)' .env; then
    warn "its DATABASE_URL points at localhost — correct for local dev, NEVER for a deploy"
  fi
else
  SECRET="$(openssl rand -base64 32)"
  cat > .env <<ENVFILE
# Generated by scripts/dev-setup.sh — local development only.
# Production uses the hosted Cloud SQL Postgres; see .env.example for its two
# connection strings. Locally both point at the same Postgres, which is
# correct: nothing sits between the app and the database here.
DATABASE_URL="${DB_URL}"
DIRECT_URL="${DB_URL}"
NEXTAUTH_URL="http://localhost:${PORT}"
NEXTAUTH_SECRET="${SECRET}"
ENVFILE
  ok "wrote .env (NEXTAUTH_SECRET generated)"
fi

# --- 3. Dependencies + schema ---------------------------------------------
say "Dependencies"
if [ -d node_modules ]; then
  ok "node_modules present — skipping install (delete it to force a reinstall)"
else
  if command -v yarn >/dev/null 2>&1; then yarn install; else npm install; fi
  ok "installed"
fi

say "Database schema"
export DATABASE_URL="$DB_URL"
export DIRECT_URL="$DB_URL"   # schema.prisma declares directUrl; db push reads it
# package.json's `prisma.schema` points the CLI at the deploy copy in public/_prisma, not at prisma/schema.prisma.
# Refresh that copy first, or generate and db push run against whatever schema the last build left there.
node scripts/copy-prisma-schema.mjs >/dev/null
ok "schema copied from prisma/schema.prisma"
npx prisma generate >/dev/null
ok "Prisma client generated"
npx prisma db push --skip-generate >/dev/null
ok "schema pushed to '$DB_NAME'"

# CHECK constraints Prisma cannot express in schema.prisma. Idempotent.
# `?schema=public` is a Prisma connection-string option; psql rejects it as an
# invalid URI query parameter, so hand psql the bare URL.
PSQL_URL="${DB_URL%%\?*}"
if command -v psql >/dev/null 2>&1; then
  psql "$PSQL_URL" -q -f prisma/wallet-constraints.sql >/dev/null 2>&1 \
    && ok "wallet constraints applied" || warn "wallet constraints skipped"
elif docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
  docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -q \
    < prisma/wallet-constraints.sql >/dev/null 2>&1 \
    && ok "wallet constraints applied" || warn "wallet constraints skipped"
fi

# --- 4. Verify -------------------------------------------------------------
# The point of the whole script: confirm the running server reaches Postgres.
say "Verifying database connectivity"
npx tsx -e "
import { PrismaClient } from '@prisma/client';
const p = new PrismaClient();
p.\$queryRaw\`SELECT 1\`
  .then(() => { console.log('    \x1b[0;32m✓\x1b[0m server can reach the database'); process.exit(0); })
  .catch((e) => { console.error('    \x1b[0;31m✗\x1b[0m ' + (e?.message ?? e).split('\n')[0]); process.exit(1); });
" || die "Database unreachable — sign-in would fail. Fix DATABASE_URL in .env."

cat <<DONE

$(printf '\033[1;32mReady.\033[0m')

  Start the app:      yarn dev
  Then open:          http://localhost:${PORT}
  Create an account:  http://localhost:${PORT}/signup

  Confirm the database at any time:
      curl http://localhost:${PORT}/api/health/db     -> {"ok":true,...}

  (/api/health and /healthz answer only "the process is up" — they stay green
   while the database is unreachable, so ask /api/health/db instead.)

  A 503 from that endpoint means sign-in will fail — it is the database,
  not your password.

DONE
