#!/usr/bin/env -S npx tsx
// Regenerate MASTER_MODE_LIST's table from the registry, or fail if it has drifted.
//
// The scope audit found the "single source of truth" three weeks stale and wrong about eight modes — it called
// tennis, golf, soccer, baseball, football, skate, surf and snowboard "Canvas 2D mockups" when every one of them is
// a Babylon mode, and listed 18 modes against a registry holding far more. A document that claims authority and is
// wrong is worse than no document: the audit's own words. So the table is generated, and drift is a failed check
// rather than something a reader discovers.
//
//   npx tsx scripts/mode-list-check.ts          — verify
//   npx tsx scripts/mode-list-check.ts --write  — regenerate
import { readFileSync, writeFileSync } from 'node:fs';

const DOC = 'MASTER_MODE_LIST.md';
const START = '<!-- MODES:BEGIN (generated by scripts/mode-list-check.ts — do not hand-edit) -->';
const END = '<!-- MODES:END -->';

const src = readFileSync('lib/babylon/modes/registry.ts', 'utf8');
const modes = [...src.matchAll(/^\s{2}([a-zA-Z0-9_]+):\s*([A-Za-z0-9_]+Mode),/gm)].map((m) => ({ key: m[1], impl: m[2] }));
// Read ONLY inside the Set literal. Slicing from the declaration to the end of the file swept up every quoted
// string after it and reported all 28 modes as enabled — which is exactly the kind of quiet wrongness this script
// exists to stop, so it is worth the four extra lines.
const decl = src.indexOf('ENABLED_BABYLON_MODES');
const open = src.indexOf('[', decl);
const close = src.indexOf(']', open);
const enabled = new Set([...src.slice(open, close).matchAll(/'([a-zA-Z0-9_]+)'/g)].map((m) => m[1]));

const rows = modes
  .sort((a, b) => a.key.localeCompare(b.key))
  .map((m) => `| \`${m.key}\` | ${m.impl} | ${enabled.has(m.key) ? 'enabled' : 'registered, not enabled'} |`);

const table = [
  `**${modes.length} modes in the registry, ${modes.filter((m) => enabled.has(m.key)).length} enabled.**`,
  `Generated from \`lib/babylon/modes/registry.ts\` — the only thing that decides what is reachable.`,
  '',
  '| key | implementation | state |',
  '|---|---|---|',
  ...rows,
].join('\n');

const doc = readFileSync(DOC, 'utf8');
const i = doc.indexOf(START), j = doc.indexOf(END);
if (i < 0 || j < 0) { console.error(`${DOC} is missing the generated block markers`); process.exit(1); }
const want = `${doc.slice(0, i + START.length)}\n${table}\n${doc.slice(j)}`;

if (process.argv.includes('--write')) {
  writeFileSync(DOC, want);
  console.log(`mode-list-check: wrote ${modes.length} modes into ${DOC}`);
} else if (doc !== want) {
  console.error(`mode-list-check: ${DOC} has drifted from the registry — run with --write`);
  process.exit(1);
} else {
  console.log(`mode-list-check: ${DOC} matches the registry (${modes.length} modes, ${[...enabled].length} enabled)`);
}
