// gen-opponent-clips — scripts/mocap/opponent-clips.json → lib/babylon/anim/authored/mocapOpponents.ts
// (EVERYONE-BODY-MOCAP-OPPONENTS, 2026-09-14). The captures stay on the owner's disk (~/Downloads/fel-mocap-sources);
// only the retargeted POSE KEYS are committed.
//
//   npx tsx scripts/mocap/gen-opponent-clips.mts [--only name,name]
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { readBvhStream, readGlbStream, LICENSE, type JointStream, type SourceKind } from './sources.mts';
import * as rtNs from '../../lib/babylon/anim/mocapRetarget.ts';
const RT = ((rtNs as unknown as { default?: typeof rtNs }).default ?? rtNs) as typeof rtNs;

interface Entry {
  name: string; replaces: string; source: SourceKind; file: string; anim?: string; from: number; to: number;
  duration?: number; loop?: boolean; mirror?: boolean; refineLoop?: [number, number]; hipsYRange?: [number, number]; note?: string;
}
const ROOT = join(process.env.HOME ?? '', 'Downloads/fel-mocap-sources');
const rootFor = (e: Entry) => (e.source === 'meshy' ? join(process.env.HOME ?? '', 'Downloads/FEL_hero_upload') : ROOT);
const OUT = 'lib/babylon/anim/authored/mocapOpponents.ts';
const only = (() => { const i = process.argv.indexOf('--only'); return i > 0 ? new Set(process.argv[i + 1].split(',')) : null; })();
const manifest = JSON.parse(readFileSync('scripts/mocap/opponent-clips.json', 'utf8')) as { clips: Entry[] };

/** Slide a loop window so its last frame's pose matches its first (hips-relative joints + their velocity). */
function refineLoop(s: JointStream, from: number, to: number, [minD, maxD]: [number, number]): [number, number] {
  const J = RT.CANON;
  const rel = (f: number) => J.map((j) => { const p = s.frames[f][j], h = s.frames[f].Hips; return [p[0] - h[0], p[1] - h[1], p[2] - h[2]]; });
  const cost = (a: number, b: number) => {
    const A = rel(a), Bf = rel(b), A2 = rel(Math.min(s.frames.length - 1, a + 2)), B2 = rel(Math.min(s.frames.length - 1, b + 2));
    let c = 0;
    for (let k = 0; k < J.length; k++) for (let d = 0; d < 3; d++) c += (A[k][d] - Bf[k][d]) ** 2 + 0.5 * ((A2[k][d] - A[k][d]) - (B2[k][d] - Bf[k][d])) ** 2;
    return c;
  };
  let best: [number, number, number] = [from, to, Infinity];
  const step = Math.max(1, Math.round(s.fps / 60));
  for (let a = Math.round((from - 0.15) * s.fps); a <= Math.round((from + 0.15) * s.fps); a += step) {
    if (a < 0) continue;
    for (let L = Math.round(minD * s.fps); L <= Math.round(maxD * s.fps); L += step) {
      const b = a + L; if (b >= s.frames.length - 2) break;
      const c = cost(a, b); if (c < best[2]) best = [a / s.fps, b / s.fps, c];
    }
  }
  return [+best[0].toFixed(3), +best[1].toFixed(3)];
}

const streams = new Map<string, JointStream>();
const out: string[] = [];
for (const e of manifest.clips) {
  if (only && !only.has(e.name)) continue;
  const key = `${e.source}:${e.file}#${e.anim ?? ''}`;
  let s = streams.get(key);
  if (!s) {
    const path = e.file.startsWith('/') ? e.file : join(rootFor(e), e.file);
    s = e.source === 'ual' || e.source === 'meshy' ? await readGlbStream(path, e.anim!, 30, e.source) : readBvhStream(path, e.source);
    streams.set(key, s);
  }
  let [from, to] = [e.from, e.to];
  if (e.loop && e.refineLoop) [from, to] = refineLoop(s, from, to, e.refineLoop);
  const r = RT.retargetToPoseKeys(s, { from, to, duration: e.duration, loop: e.loop, mirror: e.mirror, hipsYRange: e.hipsYRange });
  const hands = r.keys.map((k) => Math.max(k.hands!.Left![1], k.hands!.Right![1]));
  console.log(`${e.name.padEnd(28)} ${from.toFixed(2)}–${to.toFixed(2)}s → ${r.duration}s ${r.keys.length} keys  scale ${r.scale}  facing ${r.baseYawDeg}°  front ${r.frontSign > 0 ? '+' : '−'}  hands ${Math.min(...hands).toFixed(2)}..${Math.max(...hands).toFixed(2)} m`);
  out.push(`  {
    name: '${e.name}', replaces: '${e.replaces}', duration: ${r.duration}, loop: ${!!e.loop},
    source: '${e.source}:${e.file.split('/').pop()}${e.anim ? '#' + e.anim : ''} ${from.toFixed(2)}–${to.toFixed(2)}s${e.mirror ? ' mirrored' : ''}', license: ${JSON.stringify(LICENSE[e.source])},
    keys: [
${r.keys.map((k) => `      ${JSON.stringify(k).replace(/"(\w+)":/g, '$1: ')},`).join('\n')}
    ],
  },`);
}

if (only) { console.log('(--only: module not written)'); process.exit(0); }
writeFileSync(OUT, `// mocapOpponents — the AI bodies' motion, from REAL captures (EVERYONE-BODY-MOCAP-OPPONENTS, 2026-09-14).
// GENERATED by scripts/mocap/gen-opponent-clips.mts from scripts/mocap/opponent-clips.json — edit those, not this file.
//
// Every clip is a window of a capture retargeted to POSE KEYS (lib/babylon/anim/mocapRetarget.ts), so the two-bone
// solver fits it to whichever body plays. \`replaces\` names the authored clip an opponent plays this instead of
// (lib/babylon/anim/opponentMotion.ts). Sources and licenses ride on every clip:
//   cmu  — CMU Graphics Lab Motion Capture Database, subject 06 (basketball). Free to include in commercially-sold
//          products; the data may not be resold, even converted. (mocap.cs.cmu.edu)
//   ual  — Quaternius Universal Animation Library 2 [Standard]. CC0 1.0.
import type { Scene, Skeleton, AnimationGroup } from '@babylonjs/core';
import { buildPoseClip, type PoseKey } from '../poseClip';

export interface MocapOpponentClip {
  name: string; replaces: string; duration: number; loop: boolean; source: string; license: string; keys: PoseKey[];
}

export const MOCAP_OPPONENT_CLIPS: MocapOpponentClip[] = [
${out.join('\n')}
];

export function buildMocapOpponentClip(scene: Scene, sk: Skeleton, clip: MocapOpponentClip): AnimationGroup | null {
  return buildPoseClip(scene, sk, clip.name, clip.duration, clip.keys);
}
`);
console.log(`wrote ${OUT} (${out.length} clips)`);
