// The LearnProfile / LearnCard rows ↔ the feed's LearnState. KNOWLEDGE-FEED v2 (owner decision 2, 2026-10-06).
//
// A TYPED ADAPTER, NOT THE GENERATED CLIENT. The two models are new in prisma/schema.prisma, and the committed client
// (public/_prisma/client, a deploy artifact) is regenerated by the owner, not by this lane — so until then
// `prisma.learnProfile` does not exist in the client's types. Routes hand their `prisma` in as `unknown`, and this file
// names exactly the calls it makes (LearnDb). tsc stays clean before and after the regenerate; tests run it over an
// in-memory stand-in with the same shape. When the client has the models, nothing here needs to change.

import { reviveState, STATE_VERSION, type CardRecord, type LearnState } from '../state';
import { FRESH_LEDGER, type XpLedger } from '../accountXp';
import type { Box } from '../leitner';

export interface LearnProfileRow {
  userId: string;
  onboarded: boolean;
  topics: string[];
  likes: unknown;
  less: unknown;
  dwell: unknown;
  liked: string[];
  saved: string[];
  hidden: string[];
  xp: number;
  streakCount: number;
  streakBest: number;
  streakLastDay: number | null;
  todayDay: number;
  todayDone: string[];
  accountXpDay: number;
  accountXpToday: number;
  goalBonusDay: number;
  devices: string[];
}

export interface LearnCardRow {
  userId: string;
  cardId: string;
  views: number;
  firstDay: number;
  lastSeenAt: Date;
  box: number | null;
  dueDay: number | null;
  right: number;
  wrong: number;
  lastAnsweredDay: number | null;
}

type ProfileData = Omit<LearnProfileRow, 'userId'>;
type CardData = Omit<LearnCardRow, 'userId' | 'cardId'>;

/** Exactly the Prisma calls the learn routes make. A route's `prisma`, a transaction client, or a test stand-in. */
export interface LearnDb {
  learnProfile: {
    findUnique(args: { where: { userId: string } }): Promise<LearnProfileRow | null>;
    upsert(args: { where: { userId: string }; create: ProfileData & { userId: string }; update: Partial<ProfileData> }): Promise<unknown>;
    deleteMany(args: { where: { userId: string } }): Promise<{ count: number }>;
  };
  learnCard: {
    findMany(args: { where: { userId: string; cardId?: string } }): Promise<LearnCardRow[]>;
    upsert(args: { where: { userId_cardId: { userId: string; cardId: string } }; create: CardData & { userId: string; cardId: string }; update: CardData }): Promise<unknown>;
    deleteMany(args: { where: { userId: string } }): Promise<{ count: number }>;
  };
  playerProfile: {
    update(args: { where: { userId: string }; data: { xp: { increment: number }; lastActiveAt: Date } }): Promise<unknown>;
  };
  $queryRawUnsafe(query: string, ...values: unknown[]): Promise<unknown>;
  $transaction<T>(fn: (tx: LearnDb) => Promise<T>): Promise<T>;
}

export function cardFromRow(r: LearnCardRow): CardRecord {
  return {
    views: r.views,
    firstDay: r.firstDay,
    lastSeenMs: new Date(r.lastSeenAt).getTime(),
    ...(r.box != null
      ? { quiz: { box: r.box as Box, due: r.dueDay ?? r.firstDay, right: r.right, wrong: r.wrong, lastAnswered: r.lastAnsweredDay ?? r.firstDay } }
      : {}),
  };
}

export function cardData(rec: CardRecord): CardData {
  return {
    views: rec.views,
    firstDay: rec.firstDay,
    lastSeenAt: new Date(rec.lastSeenMs),
    box: rec.quiz?.box ?? null,
    dueDay: rec.quiz?.due ?? null,
    right: rec.quiz?.right ?? 0,
    wrong: rec.quiz?.wrong ?? 0,
    lastAnsweredDay: rec.quiz?.lastAnswered ?? null,
  };
}

/** The account's LearnState from its rows (no row: a fresh state). Revived like a device blob, so a bad JSON column
 *  reads as empty rather than throwing. `recent` is device-only and always empty here. */
export function stateFromRows(p: LearnProfileRow | null, cards: LearnCardRow[]): LearnState {
  const s = reviveState(p ? {
    v: STATE_VERSION, onboarded: p.onboarded, topics: p.topics, cards: {}, recent: [], likes: p.likes, less: p.less,
    dwell: p.dwell, liked: p.liked, saved: p.saved, hidden: p.hidden, xp: p.xp,
    streak: { count: p.streakCount, best: p.streakBest, lastDay: p.streakLastDay },
    today: { day: p.todayDay, done: p.todayDone },
  } : null);
  for (const r of cards) s.cards[r.cardId] = cardFromRow(r);
  return s;
}

export function ledgerFromRow(p: LearnProfileRow | null): XpLedger {
  return p ? { day: p.accountXpDay, today: p.accountXpToday, goalBonusDay: p.goalBonusDay } : { ...FRESH_LEDGER };
}

export function profileData(s: LearnState, ledger: XpLedger, devices: string[]): ProfileData {
  return {
    onboarded: s.onboarded,
    topics: s.topics,
    likes: s.likes,
    less: s.less,
    dwell: s.dwell,
    liked: s.liked,
    saved: s.saved,
    hidden: s.hidden,
    xp: s.xp,
    streakCount: s.streak.count,
    streakBest: s.streak.best,
    streakLastDay: s.streak.lastDay,
    todayDay: s.today.day,
    todayDone: s.today.done,
    accountXpDay: ledger.day,
    accountXpToday: ledger.today,
    goalBonusDay: ledger.goalBonusDay,
    devices,
  };
}

const sameCard = (a: CardRecord | undefined, b: CardRecord): boolean => !!a && JSON.stringify(a) === JSON.stringify(b);

/** Write the profile, and every card whose record differs from `before` (the rows as read). */
export async function saveState(db: LearnDb, userId: string, s: LearnState, ledger: XpLedger, devices: string[], before: LearnState): Promise<void> {
  const data = profileData(s, ledger, devices);
  await db.learnProfile.upsert({ where: { userId }, create: { userId, ...data }, update: data });
  for (const [cardId, rec] of Object.entries(s.cards)) {
    if (sameCard(before.cards[cardId], rec)) continue;
    const d = cardData(rec);
    await db.learnCard.upsert({ where: { userId_cardId: { userId, cardId } }, create: { userId, cardId, ...d }, update: d });
  }
}
