// GENERATED by scripts/avatar/skins/export-skins.mts — edit the script, not this file.
// The MPFB2 (MakeHuman, CC0) skin set as web maps under public/models/skins (ship pass 3, rung 2).
export type SkinFamily = 'dark' | 'medium' | 'light';
export interface SkinEntry { key: string; family: SkinFamily; sex: 'male' | 'female'; albedo: string; meanRGB: [number, number, number] }
export const SKIN_DETAIL_NORMAL = '/models/skins/detail-normal.jpg';
export const SKIN_LIBRARY: SkinEntry[] = [
  {
    "key": "dark-male",
    "family": "dark",
    "sex": "male",
    "albedo": "/models/skins/dark-male.jpg",
    "meanRGB": [
      95,
      59,
      42
    ]
  },
  {
    "key": "dark-female",
    "family": "dark",
    "sex": "female",
    "albedo": "/models/skins/dark-female.jpg",
    "meanRGB": [
      97,
      56,
      39
    ]
  },
  {
    "key": "medium-male",
    "family": "medium",
    "sex": "male",
    "albedo": "/models/skins/medium-male.jpg",
    "meanRGB": [
      209,
      163,
      134
    ]
  },
  {
    "key": "medium-female",
    "family": "medium",
    "sex": "female",
    "albedo": "/models/skins/medium-female.jpg",
    "meanRGB": [
      213,
      168,
      138
    ]
  },
  {
    "key": "light-male",
    "family": "light",
    "sex": "male",
    "albedo": "/models/skins/light-male.jpg",
    "meanRGB": [
      205,
      160,
      131
    ]
  },
  {
    "key": "light-female",
    "family": "light",
    "sex": "female",
    "albedo": "/models/skins/light-female.jpg",
    "meanRGB": [
      206,
      158,
      131
    ]
  }
];
