// Registry clip name → [existing asset clip, speedRatio].
// Current asset (elijah-hero.glb): guard, high_kick, hook, jab, jumpshot,
// roundhouse, run, walk, uppercut. Authored clips (see files/anim/authored/*)
// register under their REGISTRY names and take precedence over these aliases.

export const CLIP_ALIASES: Record<string, [string, number]> = {
  // locomotion
  idle_stand: ['guard', 0.45],
  walk_forward: ['walk', 1.0],
  run_forward: ['run', 1.0],
  run_backward: ['run', -1.0],
  sprint_forward: ['run', 1.4],
  jump_up: ['jumpshot', 1.1],
  jump_land: ['guard', 1.6],
  fall_loop: ['guard', 0.6],
  strafe_left: ['walk', 1.1],
  strafe_right: ['walk', 1.1],
  // dunk
  dunk_approach_run: ['run', 1.2],
  dunk_charge_gather: ['guard', 1.2],
  dunk_launch: ['jumpshot', 1.0],
  dunk_airborne_float: ['jumpshot', 0.35],
  dunk_score_hang: ['jumpshot', 0.5],
  dunk_land_crouch: ['guard', 1.4],
  dunk_360_scoop: ['jumpshot', 0.8],
  dunk_360_eastbay: ['jumpshot', 0.8],
  dunk_360_fake_eastbay: ['jumpshot', 0.8],
  dunk_off_board_windmill: ['jumpshot', 0.8],
  // karate
  karate_idle_stance: ['guard', 0.8],
  karate_punch_light: ['jab', 1.1],
  karate_punch_heavy: ['hook', 0.95],
  karate_kick_roundhouse: ['roundhouse', 1.0],
  karate_counter_throw: ['uppercut', 0.9],
  karate_block: ['guard', 1.6],
  karate_dodge_roll: ['guard', 1.3],
  karate_hit_react: ['guard', 2.0],
  karate_knockdown: ['guard', 0.8],
  karate_victory_pose: ['uppercut', 0.6],
  // basketball
  bball_dribble_run: ['run', 0.9],
  bball_shoot_jumper: ['jumpshot', 1.0],
  bball_score_celebrate: ['uppercut', 0.8],
  bball_defend_stance: ['guard', 0.7],
  bball_block_reach: ['jumpshot', 1.2],
  // football
  football_sprint_return: ['run', 1.35],
  football_juke_left: ['walk', 1.8],
  football_juke_right: ['walk', 1.8],
  football_spin_move: ['roundhouse', 1.2],
  football_stiff_arm: ['jab', 0.8],
  football_touchdown_spike: ['uppercut', 0.9],
  football_tackled_fall: ['guard', 1.2],
  // soccer
  soccer_dribble_jog: ['run', 0.85],
  soccer_kick_shoot: ['high_kick', 1.0],
  soccer_kick_pass: ['high_kick', 1.3],
  soccer_tackle_slide: ['guard', 1.2],
  soccer_goal_celebrate: ['uppercut', 0.8],
  soccer_header_jump: ['jumpshot', 1.1],
  // golf / baseball
  golf_address_idle: ['guard', 0.5],
  golf_swing_full: ['hook', 0.7],
  golf_putt_stroke: ['jab', 0.5],
  golf_fist_pump: ['uppercut', 0.9],
  baseball_bat_stance: ['guard', 0.6],
  baseball_swing_full: ['hook', 0.85],
  baseball_contact_drive: ['hook', 1.1],
  baseball_homer_trot: ['run', 0.7],
  // board sports
  skate_idle_cruise: ['guard', 0.5],
  skate_kickflip: ['high_kick', 1.2],
  skate_heelflip: ['high_kick', 1.1],
  skate_treflip: ['roundhouse', 1.1],
  skate_bail: ['guard', 1.5],
  snow_carve_loop: ['guard', 0.5],
  snow_jump: ['jumpshot', 1.0],
  snow_grab: ['high_kick', 0.8],
  surf_carve_loop: ['guard', 0.5],
  surf_aerial: ['jumpshot', 0.9],
  surf_tube_loop: ['guard', 0.4],
  // M39 shared board-core clips (skate/snowboard/surf ride on these five)
  board_ride_idle: ['guard', 0.6],
  board_air: ['jumpshot', 0.5],
  board_tuck: ['guard', 1.25],
  board_grab: ['jumpshot', 0.4],
  board_grind: ['guard', 1.0],
  // M40 precision-sports clips (tennis / golf / baseball / soccer)
  tennis_forehand: ['hook', 0.9],
  golf_address: ['guard', 0.5],
  golf_drive_swing: ['hook', 0.7],
  derby_bat_stance: ['guard', 0.6],
  derby_swing: ['hook', 0.85],
  derby_pitch: ['jab', 0.9],
  penalty_strike: ['high_kick', 1.0],
  keeper_dive_left: ['roundhouse', 1.1],
  keeper_dive_right: ['roundhouse', 1.1],
};

export const FALLBACK_CLIP: [string, number] = ['guard', 0.6];
