// mocapDunk — the owner's REAL dunk capture (public/mocap/dunk.json, DeepMotion,
// 92 frames @ 15 fps, 16 world joints in cm), as POSE KEYS: wrists and ankles as
// hips-relative targets and the torso's lean, frames 49..59 mapped to 0.82 s: THE JUMP — the plant, both hands taking
// the ball up the front to over the head, cocked at the apex (DUNK MOTION phase 5; the old window was the run-up at 2.67×).
// GENERATED by scripts/mocap/dunk-pose.mts — edit the script, not this file.
//
// The two-bone solver fits the targets to whichever body plays (ship pass 3,
// rung 1), so the same capture drives the shipped hero and the MPFB2 candidate.
// The global hip rise is dropped (DunkMode applies the jump arc to the root);
// only the crouch below standing is carried in hipsY.
import type { Scene, Skeleton, AnimationGroup } from '@babylonjs/core';
import { buildPoseClip, type PoseKey } from '../poseClip';

export const DUNK_MOCAP_DURATION = 0.82;
export const DUNK_MOCAP_KEYS: PoseKey[] = [
    { t: 0, bones: { Hips: [0, 22, 0], Spine: [18, 7, 0] }, hands: { Left: [-0.25, 1.03, 0.37], Right: [0.24, 1.13, -0.18] }, feet: { Left: [-0.17, 0.41, 0.22], Right: [0.11, 0.42, -0.12] }, hipsY: -0.1 },
    { t: 0.08, bones: { Hips: [0, 15, 0], Spine: [11, 7, 0] }, hands: { Left: [-0.36, 1.08, 0.37], Right: [0.24, 1.15, 0.12] }, feet: { Left: [-0.17, 0.43, 0.13], Right: [0.14, 0.41, -0.05] }, hipsY: -0.1 },
    { t: 0.16, bones: { Hips: [0, 9, 0], Spine: [5, 4, 0] }, hands: { Left: [-0.36, 1.49, 0.32], Right: [0.08, 1.53, 0.27] }, feet: { Left: [-0.18, 0.37, 0.06], Right: [0.17, 0.37, -0.1] }, hipsY: 0 },
    { t: 0.25, bones: { Hips: [0, 8, 0], Spine: [0, 1, 0] }, hands: { Left: [-0.31, 1.79, 0.2], Right: [0.05, 1.83, 0.19] }, feet: { Left: [-0.17, 0.29, -0.03], Right: [0.22, 0.32, -0.2] }, hipsY: 0 },
    { t: 0.33, bones: { Hips: [0, 6, 0], Spine: [-4, -1, 0] }, hands: { Left: [-0.27, 1.93, 0.03], Right: [0.09, 1.99, 0.01] }, feet: { Left: [-0.13, 0.29, -0.18], Right: [0.27, 0.34, -0.27] }, hipsY: 0 },
    { t: 0.41, bones: { Hips: [0, 0, 0], Spine: [-9, -1, 0] }, hands: { Left: [-0.23, 1.95, -0.09], Right: [0.13, 2, -0.11] }, feet: { Left: [-0.07, 0.44, -0.32], Right: [0.3, 0.47, -0.3] }, hipsY: 0 },
    { t: 0.49, bones: { Hips: [0, -6, 0], Spine: [-13, 1, 0] }, hands: { Left: [-0.21, 1.93, -0.14], Right: [0.18, 1.99, -0.16] }, feet: { Left: [-0.05, 0.6, -0.38], Right: [0.32, 0.58, -0.31] }, hipsY: 0 },
    { t: 0.57, bones: { Hips: [0, -9, 0], Spine: [-15, 2, 0] }, hands: { Left: [-0.21, 1.91, -0.16], Right: [0.19, 1.99, -0.17] }, feet: { Left: [-0.05, 0.62, -0.39], Right: [0.32, 0.59, -0.33] }, hipsY: 0 },
    { t: 0.66, bones: { Hips: [0, -9, 0], Spine: [-13, 1, 0] }, hands: { Left: [-0.22, 1.91, -0.14], Right: [0.17, 1.99, -0.14] }, feet: { Left: [-0.04, 0.5, -0.4], Right: [0.33, 0.48, -0.32] }, hipsY: 0 },
    { t: 0.74, bones: { Hips: [0, -13, 0], Spine: [-7, 1, 0] }, hands: { Left: [-0.23, 1.95, -0.08], Right: [0.14, 2, -0.06] }, feet: { Left: [-0.04, 0.35, -0.37], Right: [0.3, 0.33, -0.24] }, hipsY: 0 },
    { t: 0.82, bones: { Hips: [0, -19, 0], Spine: [-1, 0, 0] }, hands: { Left: [-0.22, 1.97, 0.02], Right: [0.12, 2, 0.05] }, feet: { Left: [-0.08, 0.25, -0.25], Right: [0.24, 0.24, -0.09] }, hipsY: 0 },
];

export function buildMocapDunk(scene: Scene, sk: Skeleton): AnimationGroup | null {
  return buildPoseClip(scene, sk, 'dunk_mocap', DUNK_MOCAP_DURATION, DUNK_MOCAP_KEYS);
}
