// mocapDunk — the owner's REAL dunk capture (public/mocap/dunk.json, DeepMotion,
// 92 frames @ 15 fps, 16 world joints in cm), as POSE KEYS: wrists and ankles as
// hips-relative targets and the torso's lean, frames 14..66 mapped to 1.3 s. The ball (right) hand
// carries the ball up in front of the chest from 0.65 to 0.95 s instead of the capture's wind-up behind the hip,
// and the off hand rises from 0.85 to 1 s instead of in one 50 ms step.
// GENERATED by scripts/mocap/dunk-pose.mts — edit the script, not this file.
//
// The two-bone solver fits the targets to whichever body plays (ship pass 3,
// rung 1), so the same capture drives the shipped hero and the MPFB2 candidate.
// The global hip rise is dropped (DunkMode applies the jump arc to the root);
// only the crouch below standing is carried in hipsY.
import type { Scene, Skeleton, AnimationGroup } from '@babylonjs/core';
import { buildPoseClip, type PoseKey } from '../poseClip';

export const DUNK_MOCAP_DURATION = 1.3;
export const DUNK_MOCAP_KEYS: PoseKey[] = [
    { t: 0, bones: { Hips: [0, -35, 0], Spine: [25, -20, 0] }, hands: { Left: [0, 0.96, -0.36], Right: [-0.16, 0.88, 0.46] }, feet: { Left: [-0.22, 0.08, 0.09], Right: [0.28, 0.22, -0.25] }, hipsY: -0.25 },
    { t: 0.05, bones: { Hips: [0, -35, 0], Spine: [17, -30, 0] }, hands: { Left: [0.02, 0.97, -0.42], Right: [-0.23, 0.93, 0.41] }, feet: { Left: [-0.07, 0.05, -0.19], Right: [0.25, 0.18, 0.04] }, hipsY: -0.23 },
    { t: 0.1, bones: { Hips: [0, -35, 0], Spine: [7, -30, 0] }, hands: { Left: [-0.03, 0.92, -0.35], Right: [-0.22, 0.92, 0.36] }, feet: { Left: [0.08, 0.14, -0.41], Right: [0.15, 0.2, 0.43] }, hipsY: -0.14 },
    { t: 0.15, bones: { Hips: [0, -35, 0], Spine: [-1, -30, 0] }, hands: { Left: [-0.01, 0.88, -0.27], Right: [-0.13, 0.91, 0.31] }, feet: { Left: [0.21, 0.23, -0.45], Right: [0.45, 0.53, 0.4] }, hipsY: -0.1 },
    { t: 0.2, bones: { Hips: [0, -35, 0], Spine: [-4, -30, 0] }, hands: { Left: [-0.03, 0.95, -0.24], Right: [-0.01, 1.02, 0.35] }, feet: { Left: [0.22, 0.31, -0.42], Right: [0.64, 0.67, 0.12] }, hipsY: 0 },
    { t: 0.25, bones: { Hips: [0, -35, 0], Spine: [-5, -30, 0] }, hands: { Left: [-0.08, 0.95, -0.22], Right: [0.09, 1.05, 0.39] }, feet: { Left: [0.15, 0.29, -0.42], Right: [0.4, 0.5, -0.02] }, hipsY: 0 },
    { t: 0.3, bones: { Hips: [0, -35, 0], Spine: [-5, -12, 0] }, hands: { Left: [-0.15, 0.95, -0.13], Right: [0.18, 1.11, 0.41] }, feet: { Left: [-0.01, 0.27, -0.42], Right: [0.24, 0.42, -0.07] }, hipsY: 0 },
    { t: 0.35, bones: { Hips: [0, -28, 0], Spine: [-3, 10, 0] }, hands: { Left: [-0.2, 0.97, 0.03], Right: [0.22, 1.18, 0.38] }, feet: { Left: [-0.24, 0.29, -0.38], Right: [0.16, 0.35, -0.08] }, hipsY: 0 },
    { t: 0.4, bones: { Hips: [0, -5, 0], Spine: [1, 13, 0] }, hands: { Left: [-0.19, 1.01, 0.24], Right: [0.2, 1.26, 0.36] }, feet: { Left: [-0.37, 0.34, -0.2], Right: [0.12, 0.31, -0.09] }, hipsY: 0 },
    { t: 0.45, bones: { Hips: [0, 11, 0], Spine: [4, 15, 0] }, hands: { Left: [-0.14, 1.04, 0.35], Right: [0.2, 1.33, 0.38] }, feet: { Left: [-0.36, 0.4, -0.1], Right: [0.09, 0.31, -0.09] }, hipsY: 0 },
    { t: 0.5, bones: { Hips: [0, 20, 0], Spine: [6, 15, 0] }, hands: { Left: [-0.09, 1.07, 0.4], Right: [0.2, 1.4, 0.39] }, feet: { Left: [-0.37, 0.47, -0.06], Right: [0.06, 0.33, -0.1] }, hipsY: 0 },
    { t: 0.55, bones: { Hips: [0, 25, 0], Spine: [7, 16, 0] }, hands: { Left: [-0.05, 1.11, 0.43], Right: [0.19, 1.46, 0.39] }, feet: { Left: [-0.36, 0.54, -0.04], Right: [0.05, 0.35, -0.1] }, hipsY: 0 },
    { t: 0.6, bones: { Hips: [0, 29, 0], Spine: [9, 15, 0] }, hands: { Left: [-0.02, 1.14, 0.46], Right: [0.19, 1.51, 0.38] }, feet: { Left: [-0.35, 0.58, -0.02], Right: [0.04, 0.39, -0.1] }, hipsY: 0 },
    { t: 0.65, bones: { Hips: [0, 35, 0], Spine: [12, 15, 0] }, hands: { Left: [0.02, 1.15, 0.51], Right: [0.25, 1.52, 0.34] }, feet: { Left: [-0.35, 0.6, -0.01], Right: [0.02, 0.4, -0.11] }, hipsY: 0 },
    { t: 0.7, bones: { Hips: [0, 35, 0], Spine: [13, 21, 0] }, hands: { Left: [0, 1.09, 0.52], Right: [0.22, 1.58, 0.31] }, feet: { Left: [-0.38, 0.49, -0.08], Right: [0, 0.39, -0.13] }, hipsY: 0 },
    { t: 0.75, bones: { Hips: [0, 35, 0], Spine: [14, 21, 0] }, hands: { Left: [-0.05, 1.17, 0.45], Right: [0.2, 1.63, 0.28] }, feet: { Left: [-0.33, 0.36, -0.06], Right: [-0.11, 0.45, -0.29] }, hipsY: 0 },
    { t: 0.8, bones: { Hips: [0, 35, 0], Spine: [16, 14, 0] }, hands: { Left: [-0.01, 1.36, 0.4], Right: [0.17, 1.68, 0.26] }, feet: { Left: [-0.24, 0.3, 0.25], Right: [-0.06, 0.57, -0.44] }, hipsY: 0 },
    { t: 0.85, bones: { Hips: [0, 35, 0], Spine: [21, 8, 0] }, hands: { Left: [-0.08, 1.25, 0.4], Right: [0.14, 1.73, 0.23] }, feet: { Left: [-0.16, 0.36, 0.33], Right: [0.05, 0.47, -0.29] }, hipsY: 0 },
    { t: 0.9, bones: { Hips: [0, 25, 0], Spine: [13, 6, 0] }, hands: { Left: [-0.13, 1.48, 0.25], Right: [0.11, 1.78, 0.21] }, feet: { Left: [-0.14, 0.43, 0.15], Right: [0.13, 0.41, -0.07] }, hipsY: 0 },
    { t: 0.95, bones: { Hips: [0, 18, 0], Spine: [1, 0, 0] }, hands: { Left: [-0.19, 1.72, 0.1], Right: [0.09, 1.83, 0.18] }, feet: { Left: [-0.18, 0.29, 0], Right: [0.19, 0.32, -0.24] }, hipsY: 0 },
    { t: 1, bones: { Hips: [0, 9, 0], Spine: [-9, -1, 0] }, hands: { Left: [-0.24, 1.95, -0.05], Right: [0.11, 2, -0.13] }, feet: { Left: [-0.12, 0.44, -0.3], Right: [0.25, 0.47, -0.35] }, hipsY: 0 },
    { t: 1.05, bones: { Hips: [0, 1, 0], Spine: [-15, 2, 0] }, hands: { Left: [-0.23, 1.91, -0.13], Right: [0.16, 1.99, -0.2] }, feet: { Left: [-0.12, 0.62, -0.38], Right: [0.27, 0.59, -0.38] }, hipsY: 0 },
    { t: 1.1, bones: { Hips: [0, -3, 0], Spine: [-7, 0, 0] }, hands: { Left: [-0.24, 1.95, -0.04], Right: [0.13, 2, -0.08] }, feet: { Left: [-0.1, 0.35, -0.36], Right: [0.26, 0.33, -0.29] }, hipsY: 0 },
    { t: 1.15, bones: { Hips: [0, -15, 0], Spine: [1, -2, 0] }, hands: { Left: [-0.18, 1.97, 0.12], Right: [0.18, 1.99, 0.13] }, feet: { Left: [-0.15, 0.21, -0.09], Right: [0.19, 0.2, 0.01] }, hipsY: 0 },
    { t: 1.2, bones: { Hips: [0, -27, 0], Spine: [-2, 0, 0] }, hands: { Left: [-0.13, 1.98, 0.05], Right: [0.38, 1.7, 0.22] }, feet: { Left: [-0.14, 0.21, -0.04], Right: [0.14, 0.19, 0.11] }, hipsY: 0 },
    { t: 1.25, bones: { Hips: [0, -35, 0], Spine: [-7, -4, 0] }, hands: { Left: [-0.1, 1.99, -0.14], Right: [0.28, 1.82, 0.04] }, feet: { Left: [-0.06, 0.2, -0.11], Right: [0.11, 0.19, 0.15] }, hipsY: 0 },
    { t: 1.3, bones: { Hips: [0, -35, 0], Spine: [-18, -8, 0] }, hands: { Left: [-0.13, 1.93, -0.31], Right: [0.17, 1.97, -0.17] }, feet: { Left: [0.01, 0.2, -0.19], Right: [0.11, 0.21, 0.2] }, hipsY: 0 },
];

export function buildMocapDunk(scene: Scene, sk: Skeleton): AnimationGroup | null {
  return buildPoseClip(scene, sk, 'dunk_mocap', DUNK_MOCAP_DURATION, DUNK_MOCAP_KEYS);
}
